// Generated by Haxe 4.0.0 (git build development @ af56abb)
(function () { "use strict";
var WeatherReporter = function(weatherService,locationManager) {
	this.locationManager = locationManager;
	this.weatherService = weatherService;
};
WeatherReporter.prototype = {
	report: function() {
		console.log("Main.hx:11:","Mostly clouded, 26 C\n");
	}
};
var WeatherService = function(logger,socket) {
	this.logger = logger;
	this.socket = socket;
};
var Logger = function() {
};
var WebSocket = function() {
};
var LocationManager = function(logger,gpsProvider) {
	this.logger = logger;
	this.gpsProvider = gpsProvider;
};
var GPSProvider = function() {
};
var Main = function() { };
Main.main = function() {
	var logger = new Logger();
	new WeatherReporter(new WeatherService(logger,new WebSocket()),new LocationManager(logger,new GPSProvider())).report();
};
Main.main();
})();
